language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"

before_install: 
gem update --remote bundler

script:
  - bundle exec rubocop
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
