language: ruby
rvm:
   - "2.0.0"

before_install: 
  - gem update 
  - gem install rubocop
  - gem install bundle

script:
  - bundle exec rubocop
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
