language: ruby
rvm:
   - "1.9.3"

before_install: 
  - gem update --remote bundler
  - gem install rubocop
  - gem install bundle

script:
  - bundle exec rubocop
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
